package com.aomu.printerandroid.api

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Decoded contents of the provisioning QR generated by the KitchenBot backend
 * (`GET /provision/printer-qr`). Fills every connection setting except the
 * Bluetooth printer (`printerMac`), which is a local device selection.
 */
@Serializable
data class ProvisioningPayload(
    val v: Int = 0,
    val baseUrl: String = "",
    val printerToken: String = "",
    val kitchenId: String = "",
    val printerIdentifier: String = "",
    val kitchenName: String = ""
) {
    /** Minimum fields needed for the app to talk to the API. */
    val isUsable: Boolean
        get() = baseUrl.isNotBlank() &&
            printerToken.isNotBlank() &&
            kitchenId.isNotBlank() &&
            printerIdentifier.isNotBlank()

    companion object {
        private val json = Json { ignoreUnknownKeys = true }

        /** Parses a scanned QR string; returns null if it isn't a usable payload. */
        fun parse(raw: String): ProvisioningPayload? = try {
            json.decodeFromString<ProvisioningPayload>(raw).takeIf { it.isUsable }
        } catch (_: Exception) {
            null
        }
    }
}
